### ISSUE TITLE
deployment of the project

### ISSUE THREAD

**Issue by Darshan1412** [abbasmammadov/Artificial-Barber#2]
how we can make this app for mobile or web / deploy the project anywhere so that it can be used anywhere

**Comment by abbasmammadov** [comment]
Hello,

Considering the fact that the entire process of inference (i.e. generation) takes considerable amount of time, it might not be feasible to deploy as a mobile or web, in other words some efficient way.

But, anyways you can use the main codes given in the inference.py to run the necessary generation scripts along with the necessary parameter choices which were specified and described in main.py. Therefore, by utilizing above scripts one can extend the deployment on a desired environment as well.
