### ISSUE TITLE
Error after clicking Generate button.

### ISSUE THREAD

**Issue by Dhurv870** [abbasmammadov/Artificial-Barber#3]
F:\Artificial-Barber
Loading StyleGAN2 from checkpoint: pretrained_models/ffhq.pt
Setting up Perceptual loss...
C:\Users\LENOVO\AppData\Local\Python312\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\LENOVO\AppData\Local\Python312\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or None for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing weights=VGG16_Weights.IMAGENET1K_V1. You can also use weights=VGG16_Weights.DEFAULT to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: F:\Artificial-Barber\losses\lpips\weights\v0.1\vgg.pth
...[net-lin [vgg]] initialized
...Done
Number of images: 3
Images:   0%|                                                                                                                                                                                                  | 0/3 [00:00<?, ?it/s]red.npy already exists, skipping
Images:  67%|

  | 2/3 [02:44<01:36, 96.89s/it]straight.npy already exists, skipping
Images: 100%|

| 3/3 [02:45<00:00, 55.01s/it]
Number of images: 3
Images:   0%|                                                                                                                                                                                                  | 0/3 [00:00<?, ?it/s]red.npz already exists, skipping
Images:  67%|
| 2/3 [01:55<01:07, 67.81s/it]straight.npz already exists, skipping
Images: 100%|

| 3/3 [01:55<00:00, 38.46s/it]
Loading StyleGAN2 from checkpoint: pretrained_models/ffhq.pt
F:\Artificial-Barber\models\Alignment.py:97: UserWarning: where received a uint8 condition tensor. This behavior is deprecated and will be removed in a future version of PyTorch. Use a boolean condition instead. (Triggered internally at ..\aten\src\ATen\native\TensorCompare.cpp:518.)
  new_target_final = torch.where(OB_region, torch.from_numpy(new_target_inpainted), new_target)
Traceback (most recent call last):
  File "F:\Artificial-Barber\inference.py", line 93, in <module>
    main(args)
  File "F:\Artificial-Barber\inference.py", line 30, in main
    align.align_images(im_path1, im_path2, sign=args.sign, align_more_region=False, smooth=args.smooth)
  File "F:\Artificial-Barber\models\Alignment.py", line 230, in align_images
    self.create_target_segmentation_mask(img_path1=img_path1, img_path2=img_path2, sign=sign,
  File "F:\Artificial-Barber\models\Alignment.py", line 128, in create_target_segmentation_mask
    loss.backward()
  File "C:\Users\LENOVO\AppData\Local\Python312\Lib\site-packages\torch\_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "C:\Users\LENOVO\AppData\Local\Python312\Lib\site-packages\torch\autograd\_init_.py", line 267, in backward
    _engine_run_backward(
  File "C:\Users\LENOVO\AppData\Local\Python312\Lib\site-packages\torch\autograd\graph.py", line 681, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Python312\Lib\site-packages\torch\autograd\function.py", line 289, in apply
    return user_fn(self, *args)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Artificial-Barber\models\stylegan2\op\fused_act.py", line 66, in backward
    grad_input, grad_bias = FusedLeakyReLUFunctionBackward.apply(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Python312\Lib\site-packages\torch\autograd\function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Artificial-Barber\models\stylegan2\op\fused_act.py", line 28, in forward
    grad_input = fused.fused_bias_act(
                 ^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB. GPU 0 has a total capacity of 2.00 GiB of which 0 bytes is free. Of the allocated memory 1.41 GiB is allocated by PyTorch, and 218.07 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

I am getting this error how can i solve this
my pc specs are
i5 1135G7
8gb ram
mx450 graphics card

**Comment by Dhurv870** [comment]
Please help to solve this issue

**Comment by Dhurv870** [comment]
We are badly stuck, we need the the solution as soon as possible

**Comment by abbasmammadov** [comment]
Hello and thank you very much for your interest in our work. I cannot tell exact problem, but it seems like the GPU memory is the issue. Can you please try on another gpu instance with more size?

**Comment by Dhurv870** [comment]
yes I can try
